name: Dev - Publish

on:
  push:
    branches: [dev]

jobs:
  publish:
    uses: ./.github/workflows/_docker-build.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
      artifact-metadata: write
    with:
      image_name: "ghcr.io/wakeops/mothenticate"
      dev: true
      registry_ghcr: true
